dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - memcached
  - redis-server
  - mysql
  - postgresql
addons:
  postgresql: 9.5
  apt:
    packages:
      - postgresql-9.5-postgis-2.4
      - gdal-bin

install:
  - pip install tox-travis coverage coveralls codacy-coverage
  - mysql -e 'create database django_prometheus_1;'
  - psql -U postgres -c 'CREATE DATABASE postgis'
  - psql -U postgres postgis -c 'CREATE EXTENSION IF NOT EXISTS postgis;'
script:
  - tox
after_success:
  - coverage combine .coverage django_prometheus/tests/end2end/.coverage
  - coveralls
  - coverage xml
  - python-codacy-coverage -r coverage.xml
before_deploy:
  - git checkout $TRAVIS_BRANCH
  - git fetch --unshallow
  - python update_version_from_git.py
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_existing: true
    user: __token__
    on:
      branch:
      - master
arch:
   - amd64
   - ppc64le
